# Generated by Django 5.1.1 on 2024-09-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_destacada',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
